<?php if($this->order):?>
<div>
    Order: <?php echo $this->escape($this->order->order)?><br/>
    Name: <?php echo $this->escape($this->order->name)?><br/>
    Date: <?php echo $this->order->date->format('m-d-y')?><br/>
    Amount: <?php echo $this->order->amount?> gadgets<br/>
    Total: <?php echo $this->currency($this->order->total)?>
</div>
<?php else:?>
<form method='POST' action='<?php echo $this->url()?>'>
    <input type='text' name='order' />
    <input type='submit' name='Find'> 
</form>

<?php endif;?>